### ISSUE TITLE
Additional step required to install right zookeeper package on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by dsbaars** [razorsedge/puppet-cloudera#21]
Apparently the following step is needed to get the right Zookeeper package, according to http://www.cloudera.com/content/cloudera/en/documentation/core/latest/topics/cdh_ig_cdh5_install.html

The module does not do this yet, I needed to provision my server all over again because everything depends on zookeeper :(

> Additional step for Trusty
>
> This step ensures that you get the right ZooKeeper package for the current CDH release. You need to > prioritize the Cloudera repository you have just added, such that you install the CDH version of > ZooKeeper rather than the version that is bundled with Ubuntu Trusty.

> To do this, create a file at /etc/apt/preferences.d/cloudera.pref with the following contents:
> Package: *
> Pin: release o=Cloudera, l=Cloudera
> Pin-Priority: 501

**Comment by razorsedge** [comment]
Fixed in commit 7e79e18bdadb16e6e0e1261811ae1d282f485ae0.

**Comment by razorsedge** [comment]
Released to the [Forge](https://forge.puppetlabs.com/razorsedge/cloudera) in version 2.2.1.
