### ISSUE TITLE
ripienaar-concat vs puppetlabs-concat

### ISSUE THREAD

**Issue by dsbaars** [razorsedge/puppet-cloudera#22]
One of the modules this puppet-module depends on (I performed a manual search, couldn't find which one) makes use of ripienaar/concat. This conflicts with puppetlabs/concat in my environment which a lot of other modules use. 

I did a bit  of research and apparently this is the old name of puppetlabs/concat (https://github.com/joshbeard/puppet-display/issues/4). Is there a way to resolve the conflict by specifying it somewhere in this module?

**Comment by razorsedge** [comment]
I am forced to use some fairly old dependencies at the moment (see issue #11).  I plan on updating those dependencies soon and that should fix this issue.

**Comment by razorsedge** [comment]
Fixed in commit 6dc1cfe3ec45fc9590e53790513ec39f41429f53.

**Comment by razorsedge** [comment]
This is fixed in version 3.0.0 on the [Forge](https://forge.puppetlabs.com/razorsedge/cloudera).
