### ISSUE TITLE
cloudera-scm-server-db

### ISSUE THREAD

**Issue by shankarkurli** [razorsedge/puppet-cloudera#32]
i'm using cloudera-manager-server-db-2-5.4.5-1.cm545.p0.5.el6.x86_64.rpm
couldnt find any files in var/lib/cloudera-scm-server-db/data . How to get rectify this issue.
please help me

**Comment by razorsedge** [comment]
@shankarkurli I would suggest using [Cloudera resources](https://community.cloudera.com/) to troubleshoot the issue.
