### ISSUE TITLE
Unknown variable: '::cloudera_cdh_reposerver' - deprecated language use in module

### ISSUE THREAD

**Issue by noobcontrol** [razorsedge/puppet-cloudera#42]
I get a

`Jul 17 17:36:26 kmobd2-nnode2 puppet-agent[1201]: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown variable: '::cloudera_cdh_reposerver'. at /etc/puppetlabs/code/environments/production/modules/cloudera/manifests/params.pp:24:21 on node ..
`
The reason is the strict_variable option

https://docs.puppet.com/puppet/5.0/deprecated_language.html#non-strict-variables

You should adjust your module to be able to run even with

strict_variable = true

**Comment by razorsedge** [comment]
This is being actively worked on.  Full Puppet 4 compatibility with strict_variables=true will be available soon.

**Comment by razorsedge** [comment]
Version [3.1.0](https://forge.puppet.com/razorsedge/cloudera/3.1.0/readme) has been released to the Forge.
